import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import ReactPlayer from "react-player/lazy";
import { fetchAPI } from "../utils/fetchAPI";
import Navbar from "../../components/Navbar";
import Head from "next/head";
import Master from "../../components/Master";
import Image from "next/image";
import { AiFillYoutube, AiOutlineMenu, AiOutlineSearch } from "react-icons/ai";

const play = () => {
  const [VideoDetail, setVideoDetail] = useState("");

  const router = useRouter();

  const videoID = router.query.VidID;
  useEffect(() => {
    fetchAPI(`videos?part=snippet&part=statistics&id=${videoID}`).then((data) =>
      setVideoDetail(data.items[0])
    );
  }, [videoID]);
  const [videos, setVideos] = useState([]);

  const maxresults = 50;
  useEffect(() => {
    fetchAPI(
      `search?part=snippet&type=video&maxResults=${maxresults}&q=New`
    ).then((data) => setVideos(data.items));
  }, []);

  return (
    <>
      <Head>
        <title>{VideoDetail?.snippet?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={
          "fixed grid grid-cols-3 w-[100%] bg-dark-100 h-[56px] items-center px-7 justify-between z-[10]"
        }
      >
        <div className={" flex text-text-100 text-[22px] items-center  "}>
          <div className={"text-[20px] hidden md:block mr-4"}>
            <AiOutlineMenu />
          </div>
          <div className="flex items-center font-bold text-white uppercase font-logo-f">
            <AiFillYoutube className={"text-[#ff0000] text-[30px] mr-[2px]"} />
            ZEETUBE
          </div>
        </div>
        <div className={"hidden md:flex grow max-w-[100%] justify-center"}>
          <form className="flex w-fit grow ">
            <input
              type="text"
              placeholder="Search"
              className={
                " bg-dark-100 text-text-100 font-thin  py-[6px] px-4 grow rounded-tl-full rounded-bl-full placeholder:text-text-200 placeholder:font-[400] outline outline-1 outline-event-200   focus:outline-[#046ec4]"
              }
            />
            <button
              type="submit"
              className={
                "hidden md:flex bg-dark-200 text-[#efefef] text-[24px]  px-4 items-center justify-center  outline outline-1 outline-event-200 rounded-tr-full rounded-br-full"
              }
            >
              <AiOutlineSearch />
            </button>
          </form>
          <div></div>
        </div>
      </div>
      <div className="flex gap-4 pt-[60px] overflow-y-auto">
        <div className="px-6 py-6 w-[75%] h-fit">
          <div className="h-[600px] w-full">
            <ReactPlayer
              url={`https://www.youtube.com/watch?v=${videoID}`}
              className="react-player"
              width="100%"
              height="100%"
              controls
            />
          </div>

          <div className="text-[24px] font-bold  max-w-[60ch] pt-4">
            {VideoDetail?.snippet?.title}
          </div>
          <div className="flex flex-row justify-between pt-4 font-semibold ">
            <div className="text-[18px] flex gap-6">
              <span className="flex items-center justify-center">
                <Image
                  src="/assets/skills/javascript.png"
                  height={35}
                  width={35}
                  className="overflow-hidden rounded-full"
                />
              </span>
              <span className="flex flex-col">
                <span>{VideoDetail?.snippet?.channelTitle}</span>
                <span className="text-[14px] text-event-200">
                  123k Subscribers
                </span>
              </span>
              <button className="rounded-full  bg-text-100  px-6 text-dark-100 h-[40px]">
                Subscribe
              </button>
            </div>
            <div className="text-[16px] text-[#d5caca] grid grid-cols-2 gap-4 ">
              <span>{VideoDetail?.statistics?.viewCount} views</span>
              <span>{VideoDetail?.statistics?.likeCount} likes</span>
            </div>
          </div>
          <div className="w-full p-4 text-text-200">
            {VideoDetail?.snippet?.description}
          </div>
        </div>
        <div className="w-[25%] ">
          <Master videos={videos} />
        </div>
      </div>
    </>
  );
};

export default play;
